version: "3.9"
services:
  sd:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ../sd-data:/data
      - ../sd-output:/outputs
      - sd-cache:/root/.cache
    devices:
      - "/dev/kfd"
      - "/dev/dri"
volumes:
  sd-cache:
